version: "3.7"

services:
  mysql:
    build: docker-compose/mysql
    container_name: apel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: apel
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    build: docker-compose/redis
    container_name: apel-redis
    volumes:
      - ./docker-compose/mysql:/data

  app:
    build: docker-compose/engine
    container_name: apel-app
    volumes:
      - ./:/var/www/html
    entrypoint:
      - php-fpm
    links:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: apel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    links:
      - app

  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: apel-phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"


