version: "3.7"
services:
  app:
    build:
      args:
        user: apel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: apel
    container_name: apel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - apel

  mysql:
    image: mysql
    container_name: apel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: apel
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: apel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - apel

  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: apel-phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"

networks:
  apel:
    driver: bridge
